[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$9/5/LwVAaA3hfE8JYayV0g$IRDd2h.XbfwmoEn/bQxb9RK.9NSWf0K8Qg7ZvEHfPAWVVGUzir4ZWBMN2b/F/XTKUKc0hCr3L.VN3ZfuVduEAQ

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_db_password