from . import das_lms_constants
from . import res_partner
from . import course_enrollment
from . import das_lms_academic_dashboard
from . import das_lms_advanced_analytics
from . import slide_channel_partner
from . import slide_channel
from . import product_template
from . import product_product
from . import sale_order
from . import sale_order_line
from . import das_lms_invoice_enroll_backfill
from . import account_move
from . import das_lms_link_audit
